[feat]component combine multiple emmet strings [feat} create t3 --noGit [fix] check next.config

diff --git a/bin/common b/bin/common
--- a/bin/common
+++ b/bin/common
@@ -6,8 +6,8 @@ function is_butT3r_project() {
     echo 1
   fi
   # check if use next and typescript
-  if [[ ! -f "next.config.mjs" ]]; then
-    echo "This is not a butT3r project missing next.config.mjs" >&2
+  if [[ ! -f "next.config.js" ]] && [[ ! -f "next.config.mjs" ]]; then
+    echo "This is not a butT3r project missing next.config" >&2
     echo 1
   fi
   if [[ ! -f "tsconfig.json" ]]; then
diff --git a/bin/component b/bin/component
--- a/bin/component
+++ b/bin/component
@@ -25,37 +25,34 @@ fi
 # @parseArger-declarations-end
 
 # @parseArger-utils
-_helpHasBeenPrinted=1;
-_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+_helpHasBeenPrinted=1
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
 # @parseArger-utils-end
 
 # @parseArger-parsing
 
-__cli_arg_count=$#;
+__cli_arg_count=$#
 
-die()
-{
+die() {
 	local _ret=1
-    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
-   	_ret="$2"
-    fi
+	if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+		_ret="$2"
+	fi
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
-
-begins_with_short_option()
-{
+begins_with_short_option() {
 	local first_option all_short_options=''
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # POSITIONALS ARGUMENTS
-_positionals=();
-_optional_positionals=();
-_arg_path="";
+_positionals=()
+_optional_positionals=()
+_arg_path=""
 # OPTIONALS ARGUMENTS
 _arg_directory=
 _arg_component_name=
@@ -63,331 +60,329 @@ _arg_props=()
 _arg_import=()
 _arg_emmet=()
 _arg_template=
-_one_of_arg_template=("page" "layout" "form" "table" );
+_one_of_arg_template=("page" "layout" "form" "table")
 # FLAGS
 _arg_server="on"
 _arg_dry_run="off"
 _arg_prettier="on"
 _arg_export_default="off"
 # NESTED
-_verbose_level="0";
+_verbose_level="0"
 
-
-
-print_help()
-{
-	_triggerSCHelp=1;
+print_help() {
+	_triggerSCHelp=1
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
-		_helpHasBeenPrinted=0;
+		_helpHasBeenPrinted=0
 		echo -e "create/update a component:"
-	echo -e "	path: path to the component"
-	echo -e "	--directory <directory>: subdirectory in src/components"
-	echo -e "	--component-name <component-name>: component name"
-	echo -e "	--props <props>: property definition (name:type), repeatable"
-	echo -e "	--import <import>: import statement (from:what), repeatable"
-	echo -e "	--emmet <emmet>: emmet pattern for the component, repeatable"
-	echo -e "	--template <template>: template to use (page|layout|form|table) [one of 'page' 'layout' 'form' 'table']"
-	echo -e "	--server|--client: is server component, on by default (use --client to turn it off)"
-	echo -e "	--dry-run|--no-dry-run: output to stdout"
-	echo -e "	--prettier|--no-prettier: run prettier before output, on by default (use --no-prettier to turn it off)"
-	echo -e "	--export-default|--no-export-default: export component as default"
-	echo -e "Usage :
-	$0 <path> [--directory <value>] [--component-name <value>] [--props <value>] [--import <value>] [--emmet <value>] [--template <value>] [--[no-]server] [--[no-]dry-run] [--[no-]prettier] [--[no-]export-default]";
+		echo -e "	path: path to the component"
+		echo -e "	--directory <directory>: subdirectory in src/components"
+		echo -e "	--component-name <component-name>: component name"
+		echo -e "	--props <props>: property definition (name:type), repeatable"
+		echo -e "	--import <import>: import statement (from:what), repeatable"
+		echo -e "	--emmet <emmet>: emmet pattern for the component, repeatable"
+		echo -e "	--template <template>: template to use (page|layout|form|table) [one of 'page' 'layout' 'form' 'table']"
+		echo -e "	--server|--client: is server component, on by default (use --client to turn it off)"
+		echo -e "	--dry-run|--no-dry-run: output to stdout"
+		echo -e "	--prettier|--no-prettier: run prettier before output, on by default (use --no-prettier to turn it off)"
+		echo -e "	--export-default|--no-export-default: export component as default"
+		echo -e "Usage :
+	$0 <path> [--directory <value>] [--component-name <value>] [--props <value>] [--import <value>] [--emmet <value>] [--template <value>] [--[no-]server] [--[no-]dry-run] [--[no-]prettier] [--[no-]export-default]"
 	fi
 
 }
 
 log() {
-	local _arg_msg="${1}";
-	local _arg_level="${2:-0}";
+	local _arg_msg="${1}"
+	local _arg_level="${2:-0}"
 	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
 		case "$_arg_level" in
-			-3)
-				_arg_COLOR="\033[0;31m";
-				;;
-			-2)
-				_arg_COLOR="\033[0;33m";
-				;;
-			-1)
-				_arg_COLOR="\033[1;33m";
-				;;
-			1)
-				_arg_COLOR="\033[0;32m";
-				;;
-			2)
-				_arg_COLOR="\033[1;36m";
-				;;
-			3)
-				_arg_COLOR="\033[0;36m";
-				;;
-			*)
-				_arg_COLOR="\033[0m";
-				;;
+		-3)
+			_arg_COLOR="\033[0;31m"
+			;;
+		-2)
+			_arg_COLOR="\033[0;33m"
+			;;
+		-1)
+			_arg_COLOR="\033[1;33m"
+			;;
+		1)
+			_arg_COLOR="\033[0;32m"
+			;;
+		2)
+			_arg_COLOR="\033[1;36m"
+			;;
+		3)
+			_arg_COLOR="\033[0;36m"
+			;;
+		*)
+			_arg_COLOR="\033[0m"
+			;;
 		esac
 		if [ "${_has_colors}" == "1" ]; then
-			echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+			echo -e "${_arg_COLOR}${_arg_msg}\033[0m"
 		else
-			echo "${_arg_msg}";
+			echo "${_arg_msg}"
 		fi
 	fi
 }
 
-parse_commandline()
-{
+parse_commandline() {
 	_positionals_count=0
-	while test $# -gt 0
-	do
+	while test $# -gt 0; do
 		_key="$1"
 		case "$_key" in
-			--directory)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_directory="$2"
+		--directory)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_directory="$2"
+			shift
+			;;
+		--directory=*)
+			_arg_directory="${_key##--directory=}"
+			;;
+
+		--component-name)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_component_name="$2"
+			shift
+			;;
+		--component-name=*)
+			_arg_component_name="${_key##--component-name=}"
+			;;
+
+		--props)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_props+=("$2")
+			shift
+			;;
+		--props=*)
+			_arg_props+=("${_key##--props=}")
+			;;
+
+		--import)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_import+=("$2")
+			shift
+			;;
+		--import=*)
+			_arg_import+=("${_key##--import=}")
+			;;
+
+		--emmet)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_emmet+=("$2")
+			shift
+			;;
+		--emmet=*)
+			_arg_emmet+=("${_key##--emmet=}")
+			;;
+
+		--template)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_template="$2"
+			if [[ "${#_one_of_arg_template[@]}" -gt 0 ]]; then [[ "${_one_of_arg_template[*]}" =~ (^|[[:space:]])"$_arg_template"($|[[:space:]]) ]] || die "template must be one of: page layout form table"; fi
+			shift
+			;;
+		--template=*)
+			_arg_template="${_key##--template=}"
+			if [[ "${#_one_of_arg_template[@]}" -gt 0 ]]; then [[ "${_one_of_arg_template[*]}" =~ (^|[[:space:]])"$_arg_template"($|[[:space:]]) ]] || die "template must be one of: page layout form table"; fi
+			;;
+
+		--server)
+			_arg_server="on"
+			;;
+		--client)
+			_arg_server="off"
+			;;
+		--dry-run)
+			_arg_dry_run="on"
+			;;
+		--no-dry-run)
+			_arg_dry_run="off"
+			;;
+		--prettier)
+			_arg_prettier="on"
+			;;
+		--no-prettier)
+			_arg_prettier="off"
+			;;
+		--export-default)
+			_arg_export_default="on"
+			;;
+		--no-export-default)
+			_arg_export_default="off"
+			;;
+		-h | --help)
+			print_help
+			exit 0
+			;;
+		-h*)
+			print_help
+			exit 0
+			;;
+		-v | --version)
+			print_version
+			exit 0
+			;;
+		-v*)
+			print_version
+			exit 0
+			;;
+		--verbose)
+			if [ $# -lt 2 ]; then
+				_verbose_level="$((_verbose_level + 1))"
+			else
+				_verbose_level="$2"
 				shift
-				;;
-			--directory=*)
-				_arg_directory="${_key##--directory=}"
-				;;
-			
-			--component-name)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_component_name="$2"
+			fi
+			;;
+		--quiet)
+			if [ $# -lt 2 ]; then
+				_verbose_level="$((_verbose_level - 1))"
+			else
+				_verbose_level="-$2"
 				shift
-				;;
-			--component-name=*)
-				_arg_component_name="${_key##--component-name=}"
-				;;
-			
-			--props)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_props+=("$2")
-				shift
-				;;
-			--props=*)
-				_arg_props+=("${_key##--props=}")
-				;;
-			
-			--import)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_import+=("$2")
-				shift
-				;;
-			--import=*)
-				_arg_import+=("${_key##--import=}")
-				;;
-			
-			--emmet)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_emmet+=("$2")
-				shift
-				;;
-			--emmet=*)
-				_arg_emmet+=("${_key##--emmet=}")
-				;;
-			
-			--template)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_template="$2"
-				if [[ "${#_one_of_arg_template[@]}" -gt 0 ]];then [[ "${_one_of_arg_template[*]}" =~ (^|[[:space:]])"$_arg_template"($|[[:space:]]) ]] || die "template must be one of: page layout form table";fi
-				shift
-				;;
-			--template=*)
-				_arg_template="${_key##--template=}"
-				if [[ "${#_one_of_arg_template[@]}" -gt 0 ]];then [[ "${_one_of_arg_template[*]}" =~ (^|[[:space:]])"$_arg_template"($|[[:space:]]) ]] || die "template must be one of: page layout form table";fi
-				;;
-			
-			--server)
-				_arg_server="on"
-				;;
-			--client)
-				_arg_server="off"
-				;;
-			--dry-run)
-				_arg_dry_run="on"
-				;;
-			--no-dry-run)
-				_arg_dry_run="off"
-				;;
-			--prettier)
-				_arg_prettier="on"
-				;;
-			--no-prettier)
-				_arg_prettier="off"
-				;;
-			--export-default)
-				_arg_export_default="on"
-				;;
-			--no-export-default)
-				_arg_export_default="off"
-				;;
-			-h|--help)
-				print_help;
-				exit 0;
-				;;
-			-h*)
-				print_help;
-				exit 0;
-				;;
-			-v|--version)
-				print_version;
-				exit 0;
-				;;
-			-v*)
-				print_version;
-				exit 0;
-				;;
-			--verbose)
-					if [ $# -lt 2 ];then
-						_verbose_level="$((_verbose_level + 1))";
-					else
-						_verbose_level="$2";
-						shift;
-					fi
-					;;
-				--quiet)
-					if [ $# -lt 2 ];then
-						_verbose_level="$((_verbose_level - 1))";
-					else
-						_verbose_level="-$2";
-						shift;
-					fi
-					;;
-				
-				*)
-				_last_positional="$1"
-				_positionals+=("$_last_positional")
-				_positionals_count=$((_positionals_count + 1))
-				;;
+			fi
+			;;
+
+		*)
+			_last_positional="$1"
+			_positionals+=("$_last_positional")
+			_positionals_count=$((_positionals_count + 1))
+			;;
 		esac
 		shift
 	done
 }
 
-
-handle_passed_args_count()
-{
+handle_passed_args_count() {
 	local _required_args_string="path"
-	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ]; then
 		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
 	fi
-	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ]; then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
-	${_positionals[*]}" 1;
+	${_positionals[*]}" 1
 	fi
 }
 
-
-assign_positional_args()
-{
-	local _positional_name _shift_for=$1;
-	_positional_names="_arg_path ";
+assign_positional_args() {
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_path "
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names};do
-		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
-		shift;
+	for _positional_name in ${_positional_names}; do
+		test $# -gt 0 || break
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1
+		shift
 	done
 }
 
-print_debug()
-{
+print_debug() {
 	print_help
 	# shellcheck disable=SC2145
-	echo "DEBUG: $0 $@";
-	
-	echo -e "	path: ${_arg_path}";
-	echo -e "	directory: ${_arg_directory}";
-	echo -e "	component-name: ${_arg_component_name}";
-	echo -e "	props: ${_arg_props[*]}";
-	echo -e "	import: ${_arg_import[*]}";
-	echo -e "	emmet: ${_arg_emmet[*]}";
-	echo -e "	template: ${_arg_template}";
-	echo -e "	server: ${_arg_server}";
-	echo -e "	dry-run: ${_arg_dry_run}";
-	echo -e "	prettier: ${_arg_prettier}";
-	echo -e "	export-default: ${_arg_export_default}";
+	echo "DEBUG: $0 $@"
+
+	echo -e "	path: ${_arg_path}"
+	echo -e "	directory: ${_arg_directory}"
+	echo -e "	component-name: ${_arg_component_name}"
+	echo -e "	props: ${_arg_props[*]}"
+	echo -e "	import: ${_arg_import[*]}"
+	echo -e "	emmet: ${_arg_emmet[*]}"
+	echo -e "	template: ${_arg_template}"
+	echo -e "	server: ${_arg_server}"
+	echo -e "	dry-run: ${_arg_dry_run}"
+	echo -e "	prettier: ${_arg_prettier}"
+	echo -e "	export-default: ${_arg_export_default}"
 
 }
 
-
-print_version()
-{
-	echo "0.0.1";
+print_version() {
+	echo "0.0.1"
 }
-
 
 on_interrupt() {
-	die Process aborted! 130;
+	die Process aborted! 130
 }
 
-
-parse_commandline "$@";
-handle_passed_args_count;
-assign_positional_args 1 "${_positionals[@]}";
-trap on_interrupt INT;
-
-
+parse_commandline "$@"
+handle_passed_args_count
+assign_positional_args 1 "${_positionals[@]}"
+trap on_interrupt INT
 
 # @parseArger-parsing-end
 # print_debug "$@"
 # @parseArger-end
 
-source "${_SCRIPT_DIR}/common";
-source "${_SCRIPT_DIR}/_ts-edit/common";
-source "${_SCRIPT_DIR}/_component/common";
+source "${_SCRIPT_DIR}/common"
+source "${_SCRIPT_DIR}/_ts-edit/common"
+source "${_SCRIPT_DIR}/_component/common"
 
 # Determine the target directory
-base_dir="src/components";
+base_dir="src/components"
 if [ -n "$_arg_directory" ]; then
-  base_dir="${base_dir}/${_arg_directory}";
+	base_dir="${base_dir}/${_arg_directory}"
 fi
 
 # Create the target directory if it doesn't exist
-target_dir="${base_dir}/${_arg_path}";
+target_dir="${base_dir}/${_arg_path}"
 if [ "$_arg_dry_run" = "off" ]; then
-  mkdir -p "$target_dir";
+	mkdir -p "$target_dir"
 fi
 
 # Determine the component name
-component_name="${_arg_component_name}";
+component_name="${_arg_component_name}"
 if [ -z "$component_name" ]; then
-  # Use the last part of the path as component name
-  component_name=$(basename "$_arg_path");
+	# Use the last part of the path as component name
+	component_name=$(basename "$_arg_path")
 fi
-component_name="$(format_component_name "$component_name")";
+component_name="$(format_component_name "$component_name")"
 
 # Set up the component file path
-target_file="${target_dir}/index.tsx";
+target_file="${target_dir}/index.tsx"
 
 # Build the component content
 content=""
 
 # Add use client directive if needed
 if [ "$_arg_server" = "off" ]; then
-  content+="'use client';\n\n"
+	content+="'use client';\n\n"
 fi
 
 # Add imports
 for import in "${_arg_import[@]}"; do
-  IFS=':' read -r from what <<< "$import"
-  content+="import { $what } from '$from';\n"
+	IFS=':' read -r from what <<<"$import"
+	content+="import { $what } from '$from';\n"
 done
 
 if [ -n "${_arg_import[*]}" ]; then
-  content+="\n"
+	content+="\n"
+fi
+
+_emmet=""
+# Combine emmet strings with an encapsulating div for each argument
+if [ "${#_arg_emmet[@]}" -gt 1 ]; then
+	_emmet+="div("
+	for emmet_content in "${_arg_emmet[@]}"; do
+		_emmet+="($emmet_content)"
+	done
+	_emmet+=")"
+elif [ "${#_arg_emmet[@]}" -eq 1 ]; then
+	_emmet+="${_arg_emmet[0]}"
+else
+	_emmet+="div{{/* TODO: implement $component_name */}}"
 fi
 
 # Create the component content
-component_content=$(create_component "$component_name" "${_arg_emmet[0]}" "$_arg_export_default" "${_arg_props[@]}")
+component_content=$(create_component "$component_name" "$_emmet" "$_arg_export_default" "${_arg_props[@]}")
 content+="$component_content"
 
 if [ "$_arg_prettier" = "on" ]; then
-  content=$(run_prettier "$content" || die "Failed to format content with Prettier." 1);
+	content=$(run_prettier "$content" || die "Failed to format content with Prettier." 1)
 fi
 
 if [ "$_arg_dry_run" = "on" ]; then
-  echo -e "$content"
+	echo -e "$content"
 else
-  echo -e "$content" > "$target_file"
+	echo -e "$content" >"$target_file"
 fi
