[feat] better install [fix] completion

diff --git a/utils/install b/utils/install
--- a/utils/install
+++ b/utils/install
@@ -10,238 +10,252 @@ if [ -t 1 ]; then # Check if stdout is a terminal
 	fi
 fi
 # @parseArger-declarations
-# @parseArger opt shell-rc-file "where to put the source directive" --default-value "$HOME/.bashrc" --repeat --alias install-file
+# @parseArger opt shell-rc-file "where to put the source directive" --default-value "/home/didi/.bashrc" --repeat --alias install-file
 # @parseArger flag comment "add parsearger comment" --on
+# @parseArger flag install-dependencies "install dependencies" --on --no-alias no-deps
 # @parseArger-declarations-end
 
 # @parseArger-utils
-_helpHasBeenPrinted=1;
-_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+_helpHasBeenPrinted=1
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
 # @parseArger-utils-end
 
 # @parseArger-parsing
 
-__cli_arg_count=$#;
+__cli_arg_count=$#
 
-die()
-{
+die() {
 	local _ret=1
-    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
-   	_ret="$2"
-    fi
+	if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+		_ret="$2"
+	fi
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
-
-begins_with_short_option()
-{
+begins_with_short_option() {
 	local first_option all_short_options=''
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # POSITIONALS ARGUMENTS
-_positionals=();
-_optional_positionals=();
+_positionals=()
+_optional_positionals=()
 # OPTIONALS ARGUMENTS
-_arg_shell_rc_file=("$HOME/.bashrc" )
+_arg_shell_rc_file=("/home/didi/.bashrc")
 # FLAGS
 _arg_comment="on"
+_arg_install_dependencies="on"
 # NESTED
-_verbose_level="0";
+_verbose_level="0"
 
-
-
-print_help()
-{
-	_triggerSCHelp=1;
+print_help() {
+	_triggerSCHelp=1
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
-		_helpHasBeenPrinted=0;
+		_helpHasBeenPrinted=0
 		echo -e "Install butt3r:"
-	echo -e "	--shell-rc-file|--install-file <shell-rc-file>: where to put the source directive, repeatable [default: '( $HOME/.bashrc )']"
-	echo -e "	--comment|--no-comment: add parsearger comment, on by default (use --no-comment to turn it off)"
-	echo -e "Usage :
-	$0 [--shell-rc-file <value>] [--[no-]comment]";
+		echo -e "	--shell-rc-file|--install-file <shell-rc-file>: where to put the source directive, repeatable [default: '( /home/didi/.bashrc )']"
+		echo -e "	--comment|--no-comment: add parsearger comment, on by default (use --no-comment to turn it off)"
+		echo -e "	--install-dependencies|--no-install-dependencies: install dependencies, on by default (use --no-install-dependencies to turn it off)
+		no-aliases: --no-deps,"
+		echo -e "Usage :
+	$0 [--shell-rc-file <value>] [--[no-]comment] [--[no-]install-dependencies]"
 	fi
 
 }
 
 log() {
-	local _arg_msg="${1}";
-	local _arg_level="${2:-0}";
+	local _arg_msg="${1}"
+	local _arg_level="${2:-0}"
 	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
 		case "$_arg_level" in
-			-3)
-				_arg_COLOR="[0;31m";
-				;;
-			-2)
-				_arg_COLOR="[0;33m";
-				;;
-			-1)
-				_arg_COLOR="[1;33m";
-				;;
-			1)
-				_arg_COLOR="[0;32m";
-				;;
-			2)
-				_arg_COLOR="[1;36m";
-				;;
-			3)
-				_arg_COLOR="[0;36m";
-				;;
-			*)
-				_arg_COLOR="[0m";
-				;;
+		-3)
+			_arg_COLOR="\033[0;31m"
+			;;
+		-2)
+			_arg_COLOR="\033[0;33m"
+			;;
+		-1)
+			_arg_COLOR="\033[1;33m"
+			;;
+		1)
+			_arg_COLOR="\033[0;32m"
+			;;
+		2)
+			_arg_COLOR="\033[1;36m"
+			;;
+		3)
+			_arg_COLOR="\033[0;36m"
+			;;
+		*)
+			_arg_COLOR="\033[0m"
+			;;
 		esac
 		if [ "${_has_colors}" == "1" ]; then
-			echo -e "${_arg_COLOR}${_arg_msg}[0m";
+			echo -e "${_arg_COLOR}${_arg_msg}\033[0m"
 		else
-			echo "${_arg_msg}";
+			echo "${_arg_msg}"
 		fi
 	fi
 }
 
-parse_commandline()
-{
+parse_commandline() {
 	_positionals_count=0
-	while test $# -gt 0
-	do
+	while test $# -gt 0; do
 		_key="$1"
 		case "$_key" in
-			--install-file|--shell-rc-file)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_shell_rc_file+=("$2")
+		--install-file | --shell-rc-file)
+			test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+			_arg_shell_rc_file+=("$2")
+			shift
+			;;
+		--shell-rc-file=*)
+			_arg_shell_rc_file+=("${_key##--shell-rc-file=}")
+			;;
+		--install-file=*)
+			_arg_shell_rc_file+=("${_key##--install-file=}")
+			;;
+
+		--comment)
+			_arg_comment="on"
+			;;
+		--no-comment)
+			_arg_comment="off"
+			;;
+		--install-dependencies)
+			_arg_install_dependencies="on"
+			;;
+		--no-install-dependencies | --no-deps)
+			_arg_install_dependencies="off"
+			;;
+		-h | --help)
+			print_help
+			exit 0
+			;;
+		-h*)
+			print_help
+			exit 0
+			;;
+		--verbose)
+			if [ $# -lt 2 ]; then
+				_verbose_level="$((_verbose_level + 1))"
+			else
+				_verbose_level="$2"
 				shift
-				;;
-			--shell-rc-file=*)
-				_arg_shell_rc_file+=("${_key##--shell-rc-file=}")
-				;;
-			--install-file=*)
-				_arg_shell_rc_file+=("${_key##--install-file=}")
-				;;
-			
-			--comment)
-				_arg_comment="on"
-				;;
-			--no-comment)
-				_arg_comment="off"
-				;;
-			-h|--help)
-				print_help;
-				exit 0;
-				;;
-			-h*)
-				print_help;
-				exit 0;
-				;;
-			--verbose)
-					if [ $# -lt 2 ];then
-						_verbose_level="$((_verbose_level + 1))";
-					else
-						_verbose_level="$2";
-						shift;
-					fi
-					;;
-				--quiet)
-					if [ $# -lt 2 ];then
-						_verbose_level="$((_verbose_level - 1))";
-					else
-						_verbose_level="-$2";
-						shift;
-					fi
-					;;
-				
-				*)
-				_last_positional="$1"
-				_positionals+=("$_last_positional")
-				_positionals_count=$((_positionals_count + 1))
-				;;
+			fi
+			;;
+		--quiet)
+			if [ $# -lt 2 ]; then
+				_verbose_level="$((_verbose_level - 1))"
+			else
+				_verbose_level="-$2"
+				shift
+			fi
+			;;
+
+		*)
+			_last_positional="$1"
+			_positionals+=("$_last_positional")
+			_positionals_count=$((_positionals_count + 1))
+			;;
 		esac
 		shift
 	done
 }
 
-
-handle_passed_args_count()
-{
+handle_passed_args_count() {
 	local _required_args_string=""
-	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
-		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').
-	${_positionals[*]}" 1
+	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ]; then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
 	fi
-	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ]; then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}.
-	${_positionals[*]}" 1;
+	${_positionals[*]}" 1
 	fi
 }
 
-
-assign_positional_args()
-{
-	local _positional_name _shift_for=$1;
-	_positional_names="";
+assign_positional_args() {
+	local _positional_name _shift_for=$1
+	_positional_names=""
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names};do
-		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
-		shift;
+	for _positional_name in ${_positional_names}; do
+		test $# -gt 0 || break
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1
+		shift
 	done
 }
 
-print_debug()
-{
+print_debug() {
 	print_help
 	# shellcheck disable=SC2145
-	echo "DEBUG: $0 $@";
-	
-	echo -e "	shell-rc-file: ${_arg_shell_rc_file[*]}";
-	echo -e "	comment: ${_arg_comment}";
+	echo "DEBUG: $0 $@"
+
+	echo -e "	shell-rc-file: ${_arg_shell_rc_file[*]}"
+	echo -e "	comment: ${_arg_comment}"
+	echo -e "	install-dependencies: ${_arg_install_dependencies}"
 
 }
-
 
 on_interrupt() {
-	die Process aborted! 130;
+	die Process aborted! 130
 }
 
-
-parse_commandline "$@";
-handle_passed_args_count;
-assign_positional_args 1 "${_positionals[@]}";
-trap on_interrupt INT;
-
-
+parse_commandline "$@"
+handle_passed_args_count
+assign_positional_args 1 "${_positionals[@]}"
+trap on_interrupt INT
 
 # @parseArger-parsing-end
 # print_debug "$@"
 # @parseArger-end
 
+if [ "$_arg_install_dependencies" == "on" ]; then
+	needed_pkgs=()
+	! command -v jq >/dev/null 2>&1 && needed_pkgs+=("jq")
+	! command -v yq >/dev/null 2>&1 && needed_pkgs+=("yq")
+
+	# Install only needed packages
+	if [ ${#needed_pkgs[@]} -gt 0 ]; then
+		if command -v apt-get >/dev/null 2>&1; then
+			sudo apt-get install "${needed_pkgs[@]}"
+		elif command -v dnf >/dev/null 2>&1; then
+			sudo dnf install "${needed_pkgs[@]}"
+		elif command -v pacman >/dev/null 2>&1; then
+			sudo pacman -S "${needed_pkgs[@]}"
+		elif command -v brew >/dev/null 2>&1; then
+			brew install "${needed_pkgs[@]}"
+		else
+			log "Could not detect package manager to install ${needed_pkgs[*]}\nyou will miss those dependencies" -2
+		fi
+	fi
+fi
+
 _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
 output="\nexport butt3r_DIR=\"$_dir\"
-source ${_dir}/butt3r.rc";
+source ${_dir}/butt3r.rc"
 
 if [ "$_arg_comment" != "off" ]; then
-	output="\n# butt3r${output}";
+	output="\n# butt3r${output}"
 fi
 
 for _file in "${_arg_shell_rc_file[@]}"; do
 	if [ -f "$_file" ]; then
 		if ! grep -q "butt3r" "$_file"; then
-			echo -e "$output" >> "$_file";
-			log "butt3r installed in $_file" 1;
+			echo -e "$output" >>"$_file"
+			log "butt3r installed in $_file" 1
 		else
-			log "butt3r already installed in $_file" 1;
+			log "butt3r already installed in $_file" 1
 		fi
 	else
-		log "File $_file not found" -1;
+		log "File $_file not found" -1
 	fi
 done
 
 # .rc
 if [ ! -f "${_dir}/butt3r.rc" ]; then
-	echo -e "alias butt3r=\"${_dir}/butt3r\"\n[ -f \"${_dir}/completely.bash\" ] && source \"${_dir}/completely.bash\";" > "${_dir}/butt3r.rc";
+	echo -e "alias butt3r=\"${_dir}/butt3r\"\n[ -f \"${_dir}/completely.bash\" ] && source \"${_dir}/completely.bash\";" >"${_dir}/butt3r.rc"
 fi
